[package]
name = "clearing-solana-tests"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
ark-bn254 = "0.5"
ark-groth16 = "0.5"
ark-snark = "0.5"
ark-std = "0.5"
clearing = { path = "../../clearing" }
clearing-circuits = { path = "../../clearing-circuits" }
clearing-solana-program = { path = "../program", features = ["mock-proof"] }
mollusk-svm.workspace = true
litesvm.workspace = true
solana-account = "3"
solana-instruction = "3"
solana-keypair = "3"
solana-program-error = "3"
solana-program-pack = "3"
solana-pubkey = "3"
solana-signer = "3"
solana-system-interface = { version = "2", features = ["bincode"] }
solana-transaction = "3"
solana-transaction-error = "3"
spl-token-2022-interface = "2"
spl-token-interface = "2"
uuid = { version = "1", default-features = false }
